In [3]:
### 导入numpy
import numpy as np


###  查看版本信息

In [7]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Anaconda3\\Library\\inclu

### 创建长度为10 的空间向量

In [10]:
a = np.zeros(10)
a

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

### 查看一组书的内存大小

In [12]:
print(a .itemsize)

8


### 从命令行中得到add 函数说明文档

In [13]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

###  创建长度为10 且第五个为1 的空间向量

In [16]:
a = np.zeros(10)
a[4] = 1
print(a)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### 创建一个从19 到50 的空间向量

In [18]:
a = np.arange(19,51)
print(a)

[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]


### 反转一个向量（第一个变成最后一个，倒过来）

In [22]:
a = np.arange(19,51)
a = a[::-1]
print(a)
# b = np.arange(50)


[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19]


### 创建3*3矩阵，值为0-8

In [23]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 找到数组中非零的位置索引

In [25]:
a = [1,3,50,0,3,0,6]
print(np.nonzero(a))

(array([0, 1, 2, 4, 6], dtype=int64),)
[]


### 创建3*3 单位矩阵

In [26]:
a = np.eye(3)
print(a)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 创建3*3 随机矩阵  括号内元组形式传参

In [33]:
a = np.random.random((3,3,3))
print(a)

[[[ 0.63814543  0.86565262  0.03369426]
  [ 0.19621221  0.78456205  0.11239318]
  [ 0.89845458  0.45209314  0.60724631]]

 [[ 0.76706752  0.54347345  0.86989293]
  [ 0.22932254  0.80458731  0.97550238]
  [ 0.45765694  0.89800382  0.2399148 ]]

 [[ 0.80587795  0.14185504  0.23328752]
  [ 0.75215369  0.04558414  0.61100826]
  [ 0.94911304  0.81001806  0.34924276]]]


### 创建一个10 *10 的随机数组， 并且找出最大与最小

In [36]:
a = np.random.random((10,10))
print(a)
print(a.max())
print(a.min())

[[ 0.63502577  0.96272089  0.19266092  0.65650626  0.93985514  0.2905579
   0.20599022  0.40561981  0.28130706  0.89026225]
 [ 0.58677416  0.99763123  0.08211786  0.0784852   0.73821709  0.12100193
   0.02249924  0.95127747  0.15793108  0.04086097]
 [ 0.87730977  0.45381533  0.01451196  0.71762038  0.3539797   0.49875125
   0.94005903  0.89977792  0.16438643  0.76562603]
 [ 0.57539154  0.8664714   0.03766955  0.40540333  0.82248035  0.53222093
   0.26354201  0.07518232  0.07283577  0.11816933]
 [ 0.44083236  0.78798971  0.77123292  0.87282724  0.03172259  0.3606477
   0.62392522  0.89310241  0.27690329  0.23068362]
 [ 0.05823333  0.0713041   0.92431526  0.92604267  0.46924095  0.67412702
   0.94482055  0.86316594  0.49476723  0.3893575 ]
 [ 0.94066354  0.25424809  0.27926689  0.28142554  0.4021085   0.12858855
   0.80738388  0.73990564  0.10652053  0.43907883]
 [ 0.81366848  0.98654428  0.5665566   0.82354996  0.27973552  0.69757796
   0.45625249  0.45961534  0.65951032  0.19115197]
 [

### 创建长度为30 的随机数组， 并计算平均值

In [37]:
a = np.random.random(30)
print(a)
print(a.mean())

[ 0.35194558  0.4129119   0.62347267  0.15009889  0.50351503  0.69840196
  0.51825128  0.75674851  0.13252141  0.01270972  0.62489491  0.80496762
  0.72156664  0.02098957  0.21116892  0.97226392  0.61972532  0.56159394
  0.48734     0.16221492  0.98755003  0.10514067  0.65714699  0.35201634
  0.74244891  0.55208151  0.18288228  0.49184884  0.96991828  0.53606578]
0.497480077438


### 创建一个二维数组， 其边界值为1， 其余为0

In [43]:
a = np.zeros((10,10))
print(a)
a[1:-1,1:-1] = 1   # 第一个参数指定行， 第二个参数指定列
print(a)
a[0,0]=9
a[9,9]=9
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 9.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.

### 对于一个已经存在的数组 添加一个用0 填充的边界

In [49]:
a = np.ones((5,5))
print(a)
a = np.pad(a,pad_width=2,mode='constant',constant_values = 0)  ## np.pad 的用法
print(a)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


### 以下表达式运行结果是什么

In [7]:
import numpy as np
print(0*np.nan)
print(np.inf> np.nan)
print(np.nan-np.nan)
print(0.3== 3*0.1)

nan
False
nan
False


### 创建5*5 矩阵并设置1,2,3,4 在其对角线下方

In [10]:
a = np.diag(1+ np.arange(4),k=-1)    # np.diag
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 创建8*8 矩阵 并设置成棋盘格式

In [14]:
a = np.zeros((8,8),dtype = int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 考虑一个(6,7,8)数组,其第100个元素索引(x,y,z)是什么

In [19]:
print(np.unravel_index(100,(6,7,8)))
print(np.unravel_index(100,(2,3,8)))  # 待处理

(1, 5, 4)


ValueError: invalid entry in index array

### 用title 去创建一个8*8 棋盘矩阵

In [20]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 对一个5*5 矩阵做归一化处理

In [21]:
a = np.random.random((5,5))
amax,amin = a.max(),a.min()
a= (a-amin)/(amax-amin)
print(a)

[[ 0.68948751  0.41942696  0.34463092  0.47317697  0.42636464]
 [ 0.68823902  0.56945161  0.23436589  0.51341462  0.71876713]
 [ 0.93409659  0.42962246  0.322146    0.11499856  0.4884566 ]
 [ 0.0872723   1.          0.57776949  0.83595238  0.54464457]
 [ 0.72585701  0.21690018  0.99263023  0.39347842  0.        ]]


### 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype

In [26]:
color = np.dtype([("r",np.ubyte,1),('g',np.ubyte,1),('b',np.ubyte,1),('a',np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [23]:
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                 ("b", np.ubyte, 1),
                 ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

### 将一个5*3 矩阵 和一个3*2 矩阵相乘，实矩阵乘积是什么

In [27]:
a = np.dot(np.ones((5,3)),np.ones((3,2)))
print(a)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### 给定一个一维数组， 对其3-8间所有元素全部取反

In [28]:
a = np.arange(11)
a[(3 <a) & (a<=8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
